### ISSUE TITLE
How to calculate the speedup metrics?

### ISSUE THREAD

**Issue by ff273** [LeonidasY/fast-vocabulary-transfer#1]
Hi, I think the speedup metrics probably calculate by the eval_runtime or related to eval time. But my results show that T_gen‘s  time is shorter than others. Maybe my evaluation results wrong. Sincerely appreciate your answer!

**Comment by LeonidasY** [comment]
Hi,

In our initial experimentation, we focused on the performance difference between the generic and multi-word tokenizers.

As such, we process the inputs in batches by padding them to the same maximum sequence length (in the code). Hence, there is little benefit in speed and memory for MWTs during inference.

There are many ways to achieve these benefits. In our paper, we measured speedup by conducting inference without batching with one sample at a time (not in the code). Since padding is no longer required, the shorter sequences of MWTs yield a natural boost in speedup and memory savings.

Alternatively, one can also explore other approaches such as group_by_length (smart batching) or DataCollatorWithPadding (dynamic padding) on HuggingFace or by tokenizing the entire test set before inference and padding to the longest input (not maximum sequence length). However, we did not evaluate these options.
